version: '3.3'

services:
  bokeh:
    image: epinux/wui:latest
    build:
      context: ./docker/bokeh
    environment:
      BOKEH_ALLOW_WS_ORIGIN: '*' 
      ORIGIN: 'ui.epinux.com'
      PORT: '7000'
      LOG_LEVEL: 'debug'
      PREFIX_PARAM: ''
      BOKEH_LOG_LEVEL: 'debug'
      PYTHONUNBUFFERED: 1
    volumes:
      - ./bokeh-app:/SIE
      - ./bokeh-app/entrypoint.sh:/entrypoint.sh

    ports:
      - 7000:7000
    hostname: ui
    deploy:
      restart_policy:
        condition: on-failure

